import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';
import { readdirSync } from 'fs';
import { join } from 'path';
import { getDocsBaseDir, getItemsWithOrder } from './sidebar-utils';

const pythonSdkDocsDir = join(getDocsBaseDir(), 'python-sdk');

const guidesItems = getItemsWithOrder(
  readdirSync(join(pythonSdkDocsDir, 'guides')),
  [
    'guides/installation',
    'guides/client',
    'guides/query_data',
    'guides/create_update_delete',
    'guides/branches',
    'guides/store',
    'guides/tracking',
    'guides/python-typing',
    'guides/batch',
    'guides/object-storage',
    'guides/resource-manager',
  ],
  'guides',
);

const topicsItems = getItemsWithOrder(
  readdirSync(join(pythonSdkDocsDir, 'topics')),
  [
    'topics/tracking',
    'topics/object_file',
  ],
  'topics',
);

const referenceItems = getItemsWithOrder(
  readdirSync(join(pythonSdkDocsDir, 'reference')),
  [
    'reference/config',
    'reference/templating',
  ],
  'reference',
);

const sidebars: SidebarsConfig = {
  pythonSdkSidebar: [
    {
      type: 'category',
      label: 'Python SDK docs',
      link: {
        type: 'doc',
        id: 'introduction',
      },
      items: [
        {
          type: 'category',
          label: 'Guides',
          items: guidesItems,
        },
        {
          type: 'category',
          label: 'Topics',
          items: topicsItems,
        },
        {
          type: 'category',
          label: 'Reference',
          items: [
            {
              type: 'category',
              label: 'Python SDK API',
              items: [
                {
                  type: 'autogenerated',
                  dirName: 'sdk_ref',
                },
              ],
            },
            ...referenceItems,
          ],
        },
      ],
    },
  ],
};

export default sidebars;