# Generated by "invoke backend.generate", do not edit directly

from __future__ import annotations

from typing import TYPE_CHECKING

from .protocols_base import CoreNode, CoreNodeSync

if TYPE_CHECKING:
    from infrahub_sdk.node import (
        RelationshipAttribute,
        RelationshipAttributeSync,
        RelationshipManager,
        RelationshipManagerSync,
    )

    from .protocols_base import (
        URL,
        Boolean,
        BooleanOptional,
        DateTime,
        DateTimeOptional,
        Dropdown,
        DropdownOptional,
        HashedPassword,
        Integer,
        IntegerOptional,
        IPHost,
        IPHostOptional,
        IPNetwork,
        IPNetworkOptional,
        JSONAttribute,
        JSONAttributeOptional,
        ListAttributeOptional,
        String,
        StringOptional,
    )


class BuiltinIPAddress(CoreNode):
    address: IPHost
    description: StringOptional
    ip_namespace: RelationshipAttribute[BuiltinIPNamespace]
    ip_prefix: RelationshipAttribute[BuiltinIPPrefix]
    member_of_groups: RelationshipManager[CoreGroup]
    profiles: RelationshipManager[CoreProfile]
    subscriber_of_groups: RelationshipManager[CoreGroup]


class BuiltinIPNamespace(CoreNode):
    description: StringOptional
    name: String
    ip_addresses: RelationshipManager[BuiltinIPAddress]
    ip_prefixes: RelationshipManager[BuiltinIPPrefix]
    member_of_groups: RelationshipManager[CoreGroup]
    profiles: RelationshipManager[CoreProfile]
    subscriber_of_groups: RelationshipManager[CoreGroup]


class BuiltinIPPrefix(CoreNode):
    broadcast_address: StringOptional
    description: StringOptional
    hostmask: StringOptional
    is_pool: Boolean
    is_top_level: BooleanOptional
    member_type: Dropdown
    netmask: StringOptional
    network_address: StringOptional
    prefix: IPNetwork
    utilization: IntegerOptional
    children: RelationshipManager[BuiltinIPPrefix]
    ip_addresses: RelationshipManager[BuiltinIPAddress]
    ip_namespace: RelationshipAttribute[BuiltinIPNamespace]
    member_of_groups: RelationshipManager[CoreGroup]
    parent: RelationshipAttribute[BuiltinIPPrefix]
    profiles: RelationshipManager[CoreProfile]
    resource_pool: RelationshipManager[CoreIPPool]
    subscriber_of_groups: RelationshipManager[CoreGroup]


class CoreAction(CoreNode):
    description: StringOptional
    name: String
    member_of_groups: RelationshipManager[CoreGroup]
    subscriber_of_groups: RelationshipManager[CoreGroup]
    triggers: RelationshipManager[CoreTriggerRule]


class CoreArtifactTarget(CoreNode):
    artifacts: RelationshipManager[CoreArtifact]
    member_of_groups: RelationshipManager[CoreGroup]
    subscriber_of_groups: RelationshipManager[CoreGroup]


class CoreBasePermission(CoreNode):
    description: StringOptional
    identifier: StringOptional
    member_of_groups: RelationshipManager[CoreGroup]
    roles: RelationshipManager[CoreAccountRole]
    subscriber_of_groups: RelationshipManager[CoreGroup]


class CoreCheck(CoreNode):
    conclusion: String
    created_at: DateTimeOptional
    kind: String
    label: StringOptional
    message: StringOptional
    name: StringOptional
    origin: String
    severity: String
    member_of_groups: RelationshipManager[CoreGroup]
    subscriber_of_groups: RelationshipManager[CoreGroup]
    validator: RelationshipAttribute[CoreValidator]


class CoreComment(CoreNode):
    text: String
    member_of_groups: RelationshipManager[CoreGroup]
    subscriber_of_groups: RelationshipManager[CoreGroup]


class CoreCredential(CoreNode):
    description: StringOptional
    label: StringOptional
    name: String
    member_of_groups: RelationshipManager[CoreGroup]
    subscriber_of_groups: RelationshipManager[CoreGroup]


class CoreFileObject(CoreNode):
    checksum: String
    file_name: String
    file_size: Integer
    file_type: String
    storage_id: String
    member_of_groups: RelationshipManager[CoreGroup]
    subscriber_of_groups: RelationshipManager[CoreGroup]


class CoreGenericAccount(CoreNode):
    account_type: String
    description: StringOptional
    label: StringOptional
    name: String
    password: HashedPassword
    status: Dropdown
    member_of_groups: RelationshipManager[CoreGroup]
    subscriber_of_groups: RelationshipManager[CoreGroup]


class CoreGenericRepository(CoreNode):
    commit: StringOptional
    description: StringOptional
    internal_status: Dropdown
    location: String
    name: String
    operational_status: Dropdown
    sync_status: Dropdown
    checks: RelationshipManager[CoreCheckDefinition]
    credential: RelationshipAttribute[CoreCredential]
    generators: RelationshipManager[CoreGeneratorDefinition]
    groups_objects: RelationshipManager[CoreRepositoryGroup]
    member_of_groups: RelationshipManager[CoreGroup]
    queries: RelationshipManager[CoreGraphQLQuery]
    subscriber_of_groups: RelationshipManager[CoreGroup]
    tags: RelationshipManager[BuiltinTag]
    transformations: RelationshipManager[CoreTransformation]


class CoreGroup(CoreNode):
    description: StringOptional
    group_type: String
    label: StringOptional
    name: String
    children: RelationshipManager[CoreGroup]
    members: RelationshipManager[CoreNode]
    parent: RelationshipAttribute[CoreGroup]
    subscribers: RelationshipManager[CoreNode]


class CoreIPPool(CoreNode):
    member_of_groups: RelationshipManager[CoreGroup]
    subscriber_of_groups: RelationshipManager[CoreGroup]


class CoreKeyValue(CoreNode):
    description: StringOptional
    key: String
    name: String
    value: String
    member_of_groups: RelationshipManager[CoreGroup]
    subscriber_of_groups: RelationshipManager[CoreGroup]


class CoreMenu(CoreNode):
    description: StringOptional
    icon: StringOptional
    kind: StringOptional
    label: StringOptional
    name: String
    namespace: String
    order_weight: Integer
    path: StringOptional
    protected: Boolean
    required_permissions: ListAttributeOptional
    section: String
    children: RelationshipManager[CoreMenu]
    member_of_groups: RelationshipManager[CoreGroup]
    parent: RelationshipAttribute[CoreMenu]
    subscriber_of_groups: RelationshipManager[CoreGroup]


class CoreNodeTriggerMatch(CoreNode):
    member_of_groups: RelationshipManager[CoreGroup]
    subscriber_of_groups: RelationshipManager[CoreGroup]
    trigger: RelationshipAttribute[CoreNodeTriggerRule]


class CoreObjectComponentTemplate(CoreNode):
    template_name: String
    member_of_groups: RelationshipManager[CoreGroup]
    subscriber_of_groups: RelationshipManager[CoreGroup]


class CoreObjectTemplate(CoreNode):
    template_name: String
    member_of_groups: RelationshipManager[CoreGroup]
    subscriber_of_groups: RelationshipManager[CoreGroup]


class CoreProfile(CoreNode):
    profile_name: String
    profile_priority: Integer
    member_of_groups: RelationshipManager[CoreGroup]
    subscriber_of_groups: RelationshipManager[CoreGroup]


class CoreResourcePool(CoreNode):
    description: StringOptional
    name: String
    member_of_groups: RelationshipManager[CoreGroup]
    subscriber_of_groups: RelationshipManager[CoreGroup]


class CoreTaskTarget(CoreNode):
    member_of_groups: RelationshipManager[CoreGroup]
    subscriber_of_groups: RelationshipManager[CoreGroup]


class CoreThread(CoreNode):
    label: StringOptional
    resolved: Boolean
    change: RelationshipAttribute[CoreProposedChange]
    comments: RelationshipManager[CoreThreadComment]
    member_of_groups: RelationshipManager[CoreGroup]
    subscriber_of_groups: RelationshipManager[CoreGroup]


class CoreTransformation(CoreNode):
    dependencies: ListAttributeOptional
    dependencies_complete: BooleanOptional
    description: StringOptional
    fingerprint: StringOptional
    label: StringOptional
    name: String
    timeout: Integer
    artifact_definitions: RelationshipManager[CoreArtifactDefinition]
    member_of_groups: RelationshipManager[CoreGroup]
    query: RelationshipAttribute[CoreGraphQLQuery]
    repository: RelationshipAttribute[CoreGenericRepository]
    subscriber_of_groups: RelationshipManager[CoreGroup]
    tags: RelationshipManager[BuiltinTag]


class CoreTriggerRule(CoreNode):
    active: Boolean
    branch_scope: Dropdown
    description: StringOptional
    name: String
    action: RelationshipAttribute[CoreAction]
    member_of_groups: RelationshipManager[CoreGroup]
    subscriber_of_groups: RelationshipManager[CoreGroup]


class CoreValidator(CoreNode):
    completed_at: DateTimeOptional
    conclusion: String
    label: StringOptional
    started_at: DateTimeOptional
    state: String
    checks: RelationshipManager[CoreCheck]
    member_of_groups: RelationshipManager[CoreGroup]
    proposed_change: RelationshipAttribute[CoreProposedChange]
    subscriber_of_groups: RelationshipManager[CoreGroup]


class CoreWebhook(CoreNode):
    active: Boolean
    branch_scope: Dropdown
    description: StringOptional
    event_type: String
    name: String
    node_kind: StringOptional
    url: URL
    validate_certificates: BooleanOptional
    headers: RelationshipManager[CoreKeyValue]
    member_of_groups: RelationshipManager[CoreGroup]
    subscriber_of_groups: RelationshipManager[CoreGroup]


class CoreWeightedPoolResource(CoreNode):
    allocation_weight: IntegerOptional
    member_of_groups: RelationshipManager[CoreGroup]
    subscriber_of_groups: RelationshipManager[CoreGroup]


class LineageOwner(CoreNode):
    pass


class LineageSource(CoreNode):
    pass


class BuiltinTag(CoreNode):
    description: StringOptional
    name: String
    member_of_groups: RelationshipManager[CoreGroup]
    profiles: RelationshipManager[CoreProfile]
    subscriber_of_groups: RelationshipManager[CoreGroup]


class CoreAccount(LineageOwner, LineageSource, CoreGenericAccount):
    account_type: String
    description: StringOptional
    label: StringOptional
    name: String
    password: HashedPassword
    status: Dropdown
    member_of_groups: RelationshipManager[CoreGroup]
    subscriber_of_groups: RelationshipManager[CoreGroup]


class CoreAccountGroup(LineageOwner, LineageSource, CoreGroup):
    description: StringOptional
    group_type: String
    label: StringOptional
    name: String
    origin: StringOptional
    children: RelationshipManager[CoreGroup]
    members: RelationshipManager[CoreNode]
    parent: RelationshipAttribute[CoreGroup]
    roles: RelationshipManager[CoreAccountRole]
    subscribers: RelationshipManager[CoreNode]


class CoreAccountRole(CoreNode):
    name: String
    groups: RelationshipManager[CoreAccountGroup]
    member_of_groups: RelationshipManager[CoreGroup]
    permissions: RelationshipManager[CoreBasePermission]
    subscriber_of_groups: RelationshipManager[CoreGroup]


class CoreArtifact(CoreTaskTarget):
    checksum: StringOptional
    content_type: String
    name: String
    parameters: JSONAttributeOptional
    status: String
    storage_id: StringOptional
    definition: RelationshipAttribute[CoreArtifactDefinition]
    member_of_groups: RelationshipManager[CoreGroup]
    object: RelationshipAttribute[CoreArtifactTarget]
    subscriber_of_groups: RelationshipManager[CoreGroup]


class CoreArtifactCheck(CoreCheck):
    artifact_id: StringOptional
    changed: BooleanOptional
    checksum: StringOptional
    conclusion: String
    created_at: DateTimeOptional
    kind: String
    label: StringOptional
    line_number: IntegerOptional
    message: StringOptional
    name: StringOptional
    origin: String
    severity: String
    storage_id: StringOptional
    member_of_groups: RelationshipManager[CoreGroup]
    subscriber_of_groups: RelationshipManager[CoreGroup]
    validator: RelationshipAttribute[CoreValidator]


class CoreArtifactDefinition(CoreTaskTarget):
    artifact_name: String
    content_type: String
    description: StringOptional
    fingerprint: StringOptional
    name: String
    parameters: JSONAttribute
    artifacts: RelationshipManager[CoreArtifact]
    member_of_groups: RelationshipManager[CoreGroup]
    subscriber_of_groups: RelationshipManager[CoreGroup]
    targets: RelationshipAttribute[CoreGroup]
    transformation: RelationshipAttribute[CoreTransformation]
    validators: RelationshipManager[CoreArtifactValidator]


class CoreArtifactThread(CoreThread):
    artifact_id: StringOptional
    label: StringOptional
    line_number: IntegerOptional
    resolved: Boolean
    storage_id: StringOptional
    change: RelationshipAttribute[CoreProposedChange]
    comments: RelationshipManager[CoreThreadComment]
    member_of_groups: RelationshipManager[CoreGroup]
    subscriber_of_groups: RelationshipManager[CoreGroup]


class CoreArtifactValidator(CoreValidator):
    completed_at: DateTimeOptional
    conclusion: String
    label: StringOptional
    started_at: DateTimeOptional
    state: String
    checks: RelationshipManager[CoreCheck]
    definition: RelationshipAttribute[CoreArtifactDefinition]
    member_of_groups: RelationshipManager[CoreGroup]
    proposed_change: RelationshipAttribute[CoreProposedChange]
    subscriber_of_groups: RelationshipManager[CoreGroup]


class CoreChangeComment(CoreComment):
    text: String
    change: RelationshipAttribute[CoreProposedChange]
    member_of_groups: RelationshipManager[CoreGroup]
    subscriber_of_groups: RelationshipManager[CoreGroup]


class CoreChangeThread(CoreThread):
    label: StringOptional
    resolved: Boolean
    change: RelationshipAttribute[CoreProposedChange]
    comments: RelationshipManager[CoreThreadComment]
    member_of_groups: RelationshipManager[CoreGroup]
    subscriber_of_groups: RelationshipManager[CoreGroup]


class CoreCheckDefinition(CoreTaskTarget):
    class_name: String
    description: StringOptional
    file_path: String
    name: String
    parameters: JSONAttributeOptional
    timeout: Integer
    member_of_groups: RelationshipManager[CoreGroup]
    query: RelationshipAttribute[CoreGraphQLQuery]
    repository: RelationshipAttribute[CoreGenericRepository]
    subscriber_of_groups: RelationshipManager[CoreGroup]
    tags: RelationshipManager[BuiltinTag]
    targets: RelationshipAttribute[CoreGroup]
    validators: RelationshipManager[CoreUserValidator]


class CoreCustomWebhook(CoreWebhook, CoreTaskTarget):
    active: Boolean
    branch_scope: Dropdown
    description: StringOptional
    event_type: String
    name: String
    node_kind: StringOptional
    shared_key: StringOptional
    url: URL
    validate_certificates: BooleanOptional
    headers: RelationshipManager[CoreKeyValue]
    member_of_groups: RelationshipManager[CoreGroup]
    subscriber_of_groups: RelationshipManager[CoreGroup]
    transformation: RelationshipAttribute[CoreTransformPython]


class CoreDataCheck(CoreCheck):
    conclusion: String
    conflicts: JSONAttribute
    created_at: DateTimeOptional
    enriched_conflict_id: StringOptional
    keep_branch: StringOptional
    kind: String
    label: StringOptional
    message: StringOptional
    name: StringOptional
    origin: String
    severity: String
    member_of_groups: RelationshipManager[CoreGroup]
    subscriber_of_groups: RelationshipManager[CoreGroup]
    validator: RelationshipAttribute[CoreValidator]


class CoreDataValidator(CoreValidator):
    completed_at: DateTimeOptional
    conclusion: String
    label: StringOptional
    started_at: DateTimeOptional
    state: String
    checks: RelationshipManager[CoreCheck]
    member_of_groups: RelationshipManager[CoreGroup]
    proposed_change: RelationshipAttribute[CoreProposedChange]
    subscriber_of_groups: RelationshipManager[CoreGroup]


class CoreEnvKeyValue(CoreKeyValue):
    description: StringOptional
    key: String
    name: String
    value: String
    member_of_groups: RelationshipManager[CoreGroup]
    subscriber_of_groups: RelationshipManager[CoreGroup]


class CoreFileCheck(CoreCheck):
    commit: StringOptional
    conclusion: String
    created_at: DateTimeOptional
    files: ListAttributeOptional
    kind: String
    label: StringOptional
    message: StringOptional
    name: StringOptional
    origin: String
    severity: String
    member_of_groups: RelationshipManager[CoreGroup]
    subscriber_of_groups: RelationshipManager[CoreGroup]
    validator: RelationshipAttribute[CoreValidator]


class CoreFileThread(CoreThread):
    commit: StringOptional
    file: StringOptional
    label: StringOptional
    line_number: IntegerOptional
    resolved: Boolean
    change: RelationshipAttribute[CoreProposedChange]
    comments: RelationshipManager[CoreThreadComment]
    member_of_groups: RelationshipManager[CoreGroup]
    repository: RelationshipAttribute[CoreRepository]
    subscriber_of_groups: RelationshipManager[CoreGroup]


class CoreGeneratorAction(CoreAction):
    description: StringOptional
    name: String
    generator: RelationshipAttribute[CoreGeneratorDefinition]
    member_of_groups: RelationshipManager[CoreGroup]
    subscriber_of_groups: RelationshipManager[CoreGroup]
    triggers: RelationshipManager[CoreTriggerRule]


class CoreGeneratorAwareGroup(CoreGroup):
    description: StringOptional
    group_type: String
    label: StringOptional
    name: String
    children: RelationshipManager[CoreGroup]
    members: RelationshipManager[CoreNode]
    parent: RelationshipAttribute[CoreGroup]
    subscribers: RelationshipManager[CoreNode]


class CoreGeneratorCheck(CoreCheck):
    conclusion: String
    created_at: DateTimeOptional
    instance: String
    kind: String
    label: StringOptional
    message: StringOptional
    name: StringOptional
    origin: String
    severity: String
    member_of_groups: RelationshipManager[CoreGroup]
    subscriber_of_groups: RelationshipManager[CoreGroup]
    validator: RelationshipAttribute[CoreValidator]


class CoreGeneratorDefinition(CoreTaskTarget):
    class_name: String
    convert_query_response: Boolean
    dependencies: ListAttributeOptional
    dependencies_complete: BooleanOptional
    description: StringOptional
    execute_after_merge: Boolean
    execute_in_proposed_change: Boolean
    file_path: String
    fingerprint: StringOptional
    name: String
    parameters: JSONAttribute
    instances: RelationshipManager[CoreGeneratorInstance]
    member_of_groups: RelationshipManager[CoreGroup]
    query: RelationshipAttribute[CoreGraphQLQuery]
    repository: RelationshipAttribute[CoreGenericRepository]
    subscriber_of_groups: RelationshipManager[CoreGroup]
    targets: RelationshipAttribute[CoreGroup]
    validators: RelationshipManager[CoreGeneratorValidator]


class CoreGeneratorGroup(CoreGroup):
    description: StringOptional
    group_type: String
    label: StringOptional
    name: String
    children: RelationshipManager[CoreGroup]
    members: RelationshipManager[CoreNode]
    parent: RelationshipAttribute[CoreGroup]
    subscribers: RelationshipManager[CoreNode]


class CoreGeneratorInstance(CoreTaskTarget):
    name: String
    status: String
    definition: RelationshipAttribute[CoreGeneratorDefinition]
    member_of_groups: RelationshipManager[CoreGroup]
    object: RelationshipAttribute[CoreNode]
    subscriber_of_groups: RelationshipManager[CoreGroup]


class CoreGeneratorValidator(CoreValidator):
    completed_at: DateTimeOptional
    conclusion: String
    label: StringOptional
    started_at: DateTimeOptional
    state: String
    checks: RelationshipManager[CoreCheck]
    definition: RelationshipAttribute[CoreGeneratorDefinition]
    member_of_groups: RelationshipManager[CoreGroup]
    proposed_change: RelationshipAttribute[CoreProposedChange]
    subscriber_of_groups: RelationshipManager[CoreGroup]


class CoreGlobalPermission(CoreBasePermission):
    action: Dropdown
    decision: Integer
    description: StringOptional
    identifier: StringOptional
    member_of_groups: RelationshipManager[CoreGroup]
    roles: RelationshipManager[CoreAccountRole]
    subscriber_of_groups: RelationshipManager[CoreGroup]


class CoreGraphQLQuery(CoreNode):
    depth: IntegerOptional
    description: StringOptional
    fingerprint: StringOptional
    height: IntegerOptional
    models: ListAttributeOptional
    name: String
    operations: ListAttributeOptional
    query: String
    variables: JSONAttributeOptional
    member_of_groups: RelationshipManager[CoreGroup]
    query_groups: RelationshipManager[CoreGraphQLQueryGroup]
    repository: RelationshipAttribute[CoreGenericRepository]
    subscriber_of_groups: RelationshipManager[CoreGroup]
    tags: RelationshipManager[BuiltinTag]


class CoreGraphQLQueryGroup(CoreGroup):
    description: StringOptional
    group_type: String
    label: StringOptional
    name: String
    parameters: JSONAttributeOptional
    children: RelationshipManager[CoreGroup]
    members: RelationshipManager[CoreNode]
    parent: RelationshipAttribute[CoreGroup]
    query: RelationshipAttribute[CoreGraphQLQuery]
    subscribers: RelationshipManager[CoreNode]


class CoreGroupAction(CoreAction):
    description: StringOptional
    member_action: Dropdown
    name: String
    group: RelationshipAttribute[CoreGroup]
    member_of_groups: RelationshipManager[CoreGroup]
    subscriber_of_groups: RelationshipManager[CoreGroup]
    triggers: RelationshipManager[CoreTriggerRule]


class CoreGroupTriggerRule(CoreTriggerRule):
    active: Boolean
    branch_scope: Dropdown
    description: StringOptional
    member_update: Dropdown
    name: String
    action: RelationshipAttribute[CoreAction]
    group: RelationshipAttribute[CoreGroup]
    member_of_groups: RelationshipManager[CoreGroup]
    subscriber_of_groups: RelationshipManager[CoreGroup]


class CoreIPAddressPool(CoreResourcePool, LineageSource, CoreIPPool):
    default_address_type: String
    default_prefix_length: IntegerOptional
    description: StringOptional
    name: String
    ip_namespace: RelationshipAttribute[BuiltinIPNamespace]
    member_of_groups: RelationshipManager[CoreGroup]
    resources: RelationshipManager[BuiltinIPPrefix]
    subscriber_of_groups: RelationshipManager[CoreGroup]


class CoreIPPrefixPool(CoreResourcePool, LineageSource, CoreIPPool):
    default_member_type: String
    default_prefix_length: IntegerOptional
    default_prefix_type: StringOptional
    description: StringOptional
    name: String
    ip_namespace: RelationshipAttribute[BuiltinIPNamespace]
    member_of_groups: RelationshipManager[CoreGroup]
    resources: RelationshipManager[BuiltinIPPrefix]
    subscriber_of_groups: RelationshipManager[CoreGroup]


class CoreMenuItem(CoreMenu):
    description: StringOptional
    icon: StringOptional
    kind: StringOptional
    label: StringOptional
    name: String
    namespace: String
    order_weight: Integer
    path: StringOptional
    protected: Boolean
    required_permissions: ListAttributeOptional
    section: String
    children: RelationshipManager[CoreMenu]
    member_of_groups: RelationshipManager[CoreGroup]
    parent: RelationshipAttribute[CoreMenu]
    subscriber_of_groups: RelationshipManager[CoreGroup]


class CoreNodeTriggerAttributeMatch(CoreNodeTriggerMatch):
    attribute_name: String
    value: StringOptional
    value_match: Dropdown
    value_previous: StringOptional
    member_of_groups: RelationshipManager[CoreGroup]
    subscriber_of_groups: RelationshipManager[CoreGroup]
    trigger: RelationshipAttribute[CoreNodeTriggerRule]


class CoreNodeTriggerRelationshipMatch(CoreNodeTriggerMatch):
    modification_type: Dropdown
    peer: StringOptional
    relationship_name: String
    member_of_groups: RelationshipManager[CoreGroup]
    subscriber_of_groups: RelationshipManager[CoreGroup]
    trigger: RelationshipAttribute[CoreNodeTriggerRule]


class CoreNodeTriggerRule(CoreTriggerRule):
    active: Boolean
    branch_scope: Dropdown
    description: StringOptional
    mutation_action: String
    name: String
    node_kind: String
    action: RelationshipAttribute[CoreAction]
    matches: RelationshipManager[CoreNodeTriggerMatch]
    member_of_groups: RelationshipManager[CoreGroup]
    subscriber_of_groups: RelationshipManager[CoreGroup]


class CoreNumberPool(CoreResourcePool, LineageSource):
    description: StringOptional
    end_range: Integer
    name: String
    node: String
    node_attribute: String
    pool_type: String
    start_range: Integer
    member_of_groups: RelationshipManager[CoreGroup]
    subscriber_of_groups: RelationshipManager[CoreGroup]


class CoreObjectPermission(CoreBasePermission):
    action: String
    decision: Integer
    description: StringOptional
    identifier: StringOptional
    name: String
    namespace: String
    member_of_groups: RelationshipManager[CoreGroup]
    roles: RelationshipManager[CoreAccountRole]
    subscriber_of_groups: RelationshipManager[CoreGroup]


class CoreObjectThread(CoreThread):
    label: StringOptional
    object_path: String
    resolved: Boolean
    change: RelationshipAttribute[CoreProposedChange]
    comments: RelationshipManager[CoreThreadComment]
    member_of_groups: RelationshipManager[CoreGroup]
    subscriber_of_groups: RelationshipManager[CoreGroup]


class CorePasswordCredential(CoreCredential):
    description: StringOptional
    label: StringOptional
    name: String
    password: StringOptional
    username: StringOptional
    member_of_groups: RelationshipManager[CoreGroup]
    subscriber_of_groups: RelationshipManager[CoreGroup]


class CoreProposedChange(CoreTaskTarget):
    description: StringOptional
    destination_branch: String
    is_draft: Boolean
    name: String
    source_branch: String
    state: String
    total_comments: IntegerOptional
    approved_by: RelationshipManager[CoreGenericAccount]
    comments: RelationshipManager[CoreChangeComment]
    member_of_groups: RelationshipManager[CoreGroup]
    rejected_by: RelationshipManager[CoreGenericAccount]
    reviewers: RelationshipManager[CoreGenericAccount]
    subscriber_of_groups: RelationshipManager[CoreGroup]
    threads: RelationshipManager[CoreThread]
    validations: RelationshipManager[CoreValidator]


class CoreReadOnlyRepository(LineageOwner, LineageSource, CoreGenericRepository, CoreTaskTarget):
    commit: StringOptional
    description: StringOptional
    internal_status: Dropdown
    location: String
    name: String
    operational_status: Dropdown
    ref: String
    sync_status: Dropdown
    checks: RelationshipManager[CoreCheckDefinition]
    credential: RelationshipAttribute[CoreCredential]
    generators: RelationshipManager[CoreGeneratorDefinition]
    groups_objects: RelationshipManager[CoreRepositoryGroup]
    member_of_groups: RelationshipManager[CoreGroup]
    queries: RelationshipManager[CoreGraphQLQuery]
    subscriber_of_groups: RelationshipManager[CoreGroup]
    tags: RelationshipManager[BuiltinTag]
    transformations: RelationshipManager[CoreTransformation]


class CoreRepository(LineageOwner, LineageSource, CoreGenericRepository, CoreTaskTarget):
    commit: StringOptional
    default_branch: String
    description: StringOptional
    internal_status: Dropdown
    location: String
    name: String
    operational_status: Dropdown
    sync_status: Dropdown
    checks: RelationshipManager[CoreCheckDefinition]
    credential: RelationshipAttribute[CoreCredential]
    generators: RelationshipManager[CoreGeneratorDefinition]
    groups_objects: RelationshipManager[CoreRepositoryGroup]
    member_of_groups: RelationshipManager[CoreGroup]
    queries: RelationshipManager[CoreGraphQLQuery]
    subscriber_of_groups: RelationshipManager[CoreGroup]
    tags: RelationshipManager[BuiltinTag]
    transformations: RelationshipManager[CoreTransformation]


class CoreRepositoryGroup(CoreGroup):
    content: Dropdown
    description: StringOptional
    group_type: String
    label: StringOptional
    name: String
    children: RelationshipManager[CoreGroup]
    members: RelationshipManager[CoreNode]
    parent: RelationshipAttribute[CoreGroup]
    repository: RelationshipAttribute[CoreGenericRepository]
    subscribers: RelationshipManager[CoreNode]


class CoreRepositoryValidator(CoreValidator):
    completed_at: DateTimeOptional
    conclusion: String
    label: StringOptional
    started_at: DateTimeOptional
    state: String
    checks: RelationshipManager[CoreCheck]
    member_of_groups: RelationshipManager[CoreGroup]
    proposed_change: RelationshipAttribute[CoreProposedChange]
    repository: RelationshipAttribute[CoreGenericRepository]
    subscriber_of_groups: RelationshipManager[CoreGroup]


class CoreSchemaCheck(CoreCheck):
    conclusion: String
    conflicts: JSONAttribute
    created_at: DateTimeOptional
    enriched_conflict_id: StringOptional
    kind: String
    label: StringOptional
    message: StringOptional
    name: StringOptional
    origin: String
    severity: String
    member_of_groups: RelationshipManager[CoreGroup]
    subscriber_of_groups: RelationshipManager[CoreGroup]
    validator: RelationshipAttribute[CoreValidator]


class CoreSchemaValidator(CoreValidator):
    completed_at: DateTimeOptional
    conclusion: String
    label: StringOptional
    started_at: DateTimeOptional
    state: String
    checks: RelationshipManager[CoreCheck]
    member_of_groups: RelationshipManager[CoreGroup]
    proposed_change: RelationshipAttribute[CoreProposedChange]
    subscriber_of_groups: RelationshipManager[CoreGroup]


class CoreStandardCheck(CoreCheck):
    conclusion: String
    created_at: DateTimeOptional
    kind: String
    label: StringOptional
    message: StringOptional
    name: StringOptional
    origin: String
    severity: String
    member_of_groups: RelationshipManager[CoreGroup]
    subscriber_of_groups: RelationshipManager[CoreGroup]
    validator: RelationshipAttribute[CoreValidator]


class CoreStandardGroup(CoreGroup):
    description: StringOptional
    group_type: String
    label: StringOptional
    name: String
    children: RelationshipManager[CoreGroup]
    members: RelationshipManager[CoreNode]
    parent: RelationshipAttribute[CoreGroup]
    subscribers: RelationshipManager[CoreNode]


class CoreStandardWebhook(CoreWebhook, CoreTaskTarget):
    active: Boolean
    branch_scope: Dropdown
    description: StringOptional
    event_type: String
    name: String
    node_kind: StringOptional
    shared_key: String
    url: URL
    validate_certificates: BooleanOptional
    headers: RelationshipManager[CoreKeyValue]
    member_of_groups: RelationshipManager[CoreGroup]
    subscriber_of_groups: RelationshipManager[CoreGroup]


class CoreStaticKeyValue(CoreKeyValue):
    description: StringOptional
    key: String
    name: String
    value: String
    member_of_groups: RelationshipManager[CoreGroup]
    subscriber_of_groups: RelationshipManager[CoreGroup]


class CoreThreadComment(CoreComment):
    text: String
    member_of_groups: RelationshipManager[CoreGroup]
    subscriber_of_groups: RelationshipManager[CoreGroup]
    thread: RelationshipAttribute[CoreThread]


class CoreTransformJinja2(CoreTransformation):
    dependencies: ListAttributeOptional
    dependencies_complete: BooleanOptional
    description: StringOptional
    fingerprint: StringOptional
    label: StringOptional
    name: String
    template_path: String
    timeout: Integer
    artifact_definitions: RelationshipManager[CoreArtifactDefinition]
    member_of_groups: RelationshipManager[CoreGroup]
    query: RelationshipAttribute[CoreGraphQLQuery]
    repository: RelationshipAttribute[CoreGenericRepository]
    subscriber_of_groups: RelationshipManager[CoreGroup]
    tags: RelationshipManager[BuiltinTag]


class CoreTransformPython(CoreTransformation):
    class_name: String
    convert_query_response: Boolean
    dependencies: ListAttributeOptional
    dependencies_complete: BooleanOptional
    description: StringOptional
    file_path: String
    fingerprint: StringOptional
    label: StringOptional
    name: String
    timeout: Integer
    artifact_definitions: RelationshipManager[CoreArtifactDefinition]
    member_of_groups: RelationshipManager[CoreGroup]
    query: RelationshipAttribute[CoreGraphQLQuery]
    repository: RelationshipAttribute[CoreGenericRepository]
    subscriber_of_groups: RelationshipManager[CoreGroup]
    tags: RelationshipManager[BuiltinTag]


class CoreUserValidator(CoreValidator):
    completed_at: DateTimeOptional
    conclusion: String
    label: StringOptional
    started_at: DateTimeOptional
    state: String
    check_definition: RelationshipAttribute[CoreCheckDefinition]
    checks: RelationshipManager[CoreCheck]
    member_of_groups: RelationshipManager[CoreGroup]
    proposed_change: RelationshipAttribute[CoreProposedChange]
    repository: RelationshipAttribute[CoreGenericRepository]
    subscriber_of_groups: RelationshipManager[CoreGroup]


class InternalAccountToken(CoreNode):
    expiration: DateTimeOptional
    name: StringOptional
    token: String
    account: RelationshipAttribute[CoreGenericAccount]
    member_of_groups: RelationshipManager[CoreGroup]
    subscriber_of_groups: RelationshipManager[CoreGroup]


class InternalExternalIdentity(CoreNode):
    protocol: String
    provider_name: String
    sub: String
    account: RelationshipAttribute[CoreGenericAccount]
    member_of_groups: RelationshipManager[CoreGroup]
    subscriber_of_groups: RelationshipManager[CoreGroup]


class InternalIPPrefixAvailable(BuiltinIPPrefix):
    broadcast_address: StringOptional
    description: StringOptional
    hostmask: StringOptional
    is_pool: Boolean
    is_top_level: BooleanOptional
    member_type: Dropdown
    netmask: StringOptional
    network_address: StringOptional
    prefix: IPNetwork
    utilization: IntegerOptional
    children: RelationshipManager[BuiltinIPPrefix]
    ip_addresses: RelationshipManager[BuiltinIPAddress]
    ip_namespace: RelationshipAttribute[BuiltinIPNamespace]
    member_of_groups: RelationshipManager[CoreGroup]
    parent: RelationshipAttribute[BuiltinIPPrefix]
    profiles: RelationshipManager[CoreProfile]
    resource_pool: RelationshipManager[CoreIPPool]
    subscriber_of_groups: RelationshipManager[CoreGroup]


class InternalIPRangeAvailable(BuiltinIPAddress):
    address: IPHost
    description: StringOptional
    last_address: IPHost
    ip_namespace: RelationshipAttribute[BuiltinIPNamespace]
    ip_prefix: RelationshipAttribute[BuiltinIPPrefix]
    member_of_groups: RelationshipManager[CoreGroup]
    profiles: RelationshipManager[CoreProfile]
    subscriber_of_groups: RelationshipManager[CoreGroup]


class InternalRefreshToken(CoreNode):
    expiration: DateTime
    account: RelationshipAttribute[CoreGenericAccount]
    member_of_groups: RelationshipManager[CoreGroup]
    subscriber_of_groups: RelationshipManager[CoreGroup]


class IpamNamespace(BuiltinIPNamespace):
    default: BooleanOptional
    description: StringOptional
    name: String
    ip_addresses: RelationshipManager[BuiltinIPAddress]
    ip_prefixes: RelationshipManager[BuiltinIPPrefix]
    member_of_groups: RelationshipManager[CoreGroup]
    profiles: RelationshipManager[CoreProfile]
    subscriber_of_groups: RelationshipManager[CoreGroup]


class ProfileBuiltinIPAddress(LineageSource, CoreProfile, CoreNode):
    address: IPHostOptional
    description: StringOptional
    profile_name: String
    profile_priority: Integer
    ip_namespace: RelationshipAttribute[BuiltinIPNamespace]
    member_of_groups: RelationshipManager[CoreGroup]
    related_nodes: RelationshipManager[BuiltinIPAddress]
    subscriber_of_groups: RelationshipManager[CoreGroup]


class ProfileBuiltinIPPrefix(LineageSource, CoreProfile, CoreNode):
    description: StringOptional
    is_pool: BooleanOptional
    member_type: DropdownOptional
    prefix: IPNetworkOptional
    profile_name: String
    profile_priority: Integer
    ip_namespace: RelationshipAttribute[BuiltinIPNamespace]
    member_of_groups: RelationshipManager[CoreGroup]
    related_nodes: RelationshipManager[BuiltinIPPrefix]
    subscriber_of_groups: RelationshipManager[CoreGroup]


class ProfileBuiltinTag(LineageSource, CoreProfile, CoreNode):
    description: StringOptional
    profile_name: String
    profile_priority: Integer
    member_of_groups: RelationshipManager[CoreGroup]
    related_nodes: RelationshipManager[BuiltinTag]
    subscriber_of_groups: RelationshipManager[CoreGroup]


class ProfileIpamNamespace(LineageSource, CoreProfile, CoreNode):
    description: StringOptional
    profile_name: String
    profile_priority: Integer
    ip_addresses: RelationshipManager[BuiltinIPAddress]
    ip_prefixes: RelationshipManager[BuiltinIPPrefix]
    member_of_groups: RelationshipManager[CoreGroup]
    related_nodes: RelationshipManager[IpamNamespace]
    subscriber_of_groups: RelationshipManager[CoreGroup]


class BuiltinIPAddressSync(CoreNodeSync):
    address: IPHost
    description: StringOptional
    ip_namespace: RelationshipAttributeSync[BuiltinIPNamespaceSync]
    ip_prefix: RelationshipAttributeSync[BuiltinIPPrefixSync]
    member_of_groups: RelationshipManagerSync[CoreGroupSync]
    profiles: RelationshipManagerSync[CoreProfileSync]
    subscriber_of_groups: RelationshipManagerSync[CoreGroupSync]


class BuiltinIPNamespaceSync(CoreNodeSync):
    description: StringOptional
    name: String
    ip_addresses: RelationshipManagerSync[BuiltinIPAddressSync]
    ip_prefixes: RelationshipManagerSync[BuiltinIPPrefixSync]
    member_of_groups: RelationshipManagerSync[CoreGroupSync]
    profiles: RelationshipManagerSync[CoreProfileSync]
    subscriber_of_groups: RelationshipManagerSync[CoreGroupSync]


class BuiltinIPPrefixSync(CoreNodeSync):
    broadcast_address: StringOptional
    description: StringOptional
    hostmask: StringOptional
    is_pool: Boolean
    is_top_level: BooleanOptional
    member_type: Dropdown
    netmask: StringOptional
    network_address: StringOptional
    prefix: IPNetwork
    utilization: IntegerOptional
    children: RelationshipManagerSync[BuiltinIPPrefixSync]
    ip_addresses: RelationshipManagerSync[BuiltinIPAddressSync]
    ip_namespace: RelationshipAttributeSync[BuiltinIPNamespaceSync]
    member_of_groups: RelationshipManagerSync[CoreGroupSync]
    parent: RelationshipAttributeSync[BuiltinIPPrefixSync]
    profiles: RelationshipManagerSync[CoreProfileSync]
    resource_pool: RelationshipManagerSync[CoreIPPoolSync]
    subscriber_of_groups: RelationshipManagerSync[CoreGroupSync]


class CoreActionSync(CoreNodeSync):
    description: StringOptional
    name: String
    member_of_groups: RelationshipManagerSync[CoreGroupSync]
    subscriber_of_groups: RelationshipManagerSync[CoreGroupSync]
    triggers: RelationshipManagerSync[CoreTriggerRuleSync]


class CoreArtifactTargetSync(CoreNodeSync):
    artifacts: RelationshipManagerSync[CoreArtifactSync]
    member_of_groups: RelationshipManagerSync[CoreGroupSync]
    subscriber_of_groups: RelationshipManagerSync[CoreGroupSync]


class CoreBasePermissionSync(CoreNodeSync):
    description: StringOptional
    identifier: StringOptional
    member_of_groups: RelationshipManagerSync[CoreGroupSync]
    roles: RelationshipManagerSync[CoreAccountRoleSync]
    subscriber_of_groups: RelationshipManagerSync[CoreGroupSync]


class CoreCheckSync(CoreNodeSync):
    conclusion: String
    created_at: DateTimeOptional
    kind: String
    label: StringOptional
    message: StringOptional
    name: StringOptional
    origin: String
    severity: String
    member_of_groups: RelationshipManagerSync[CoreGroupSync]
    subscriber_of_groups: RelationshipManagerSync[CoreGroupSync]
    validator: RelationshipAttributeSync[CoreValidatorSync]


class CoreCommentSync(CoreNodeSync):
    text: String
    member_of_groups: RelationshipManagerSync[CoreGroupSync]
    subscriber_of_groups: RelationshipManagerSync[CoreGroupSync]


class CoreCredentialSync(CoreNodeSync):
    description: StringOptional
    label: StringOptional
    name: String
    member_of_groups: RelationshipManagerSync[CoreGroupSync]
    subscriber_of_groups: RelationshipManagerSync[CoreGroupSync]


class CoreFileObjectSync(CoreNodeSync):
    checksum: String
    file_name: String
    file_size: Integer
    file_type: String
    storage_id: String
    member_of_groups: RelationshipManagerSync[CoreGroupSync]
    subscriber_of_groups: RelationshipManagerSync[CoreGroupSync]


class CoreGenericAccountSync(CoreNodeSync):
    account_type: String
    description: StringOptional
    label: StringOptional
    name: String
    password: HashedPassword
    status: Dropdown
    member_of_groups: RelationshipManagerSync[CoreGroupSync]
    subscriber_of_groups: RelationshipManagerSync[CoreGroupSync]


class CoreGenericRepositorySync(CoreNodeSync):
    commit: StringOptional
    description: StringOptional
    internal_status: Dropdown
    location: String
    name: String
    operational_status: Dropdown
    sync_status: Dropdown
    checks: RelationshipManagerSync[CoreCheckDefinitionSync]
    credential: RelationshipAttributeSync[CoreCredentialSync]
    generators: RelationshipManagerSync[CoreGeneratorDefinitionSync]
    groups_objects: RelationshipManagerSync[CoreRepositoryGroupSync]
    member_of_groups: RelationshipManagerSync[CoreGroupSync]
    queries: RelationshipManagerSync[CoreGraphQLQuerySync]
    subscriber_of_groups: RelationshipManagerSync[CoreGroupSync]
    tags: RelationshipManagerSync[BuiltinTagSync]
    transformations: RelationshipManagerSync[CoreTransformationSync]


class CoreGroupSync(CoreNodeSync):
    description: StringOptional
    group_type: String
    label: StringOptional
    name: String
    children: RelationshipManagerSync[CoreGroupSync]
    members: RelationshipManagerSync[CoreNodeSync]
    parent: RelationshipAttributeSync[CoreGroupSync]
    subscribers: RelationshipManagerSync[CoreNodeSync]


class CoreIPPoolSync(CoreNodeSync):
    member_of_groups: RelationshipManagerSync[CoreGroupSync]
    subscriber_of_groups: RelationshipManagerSync[CoreGroupSync]


class CoreKeyValueSync(CoreNodeSync):
    description: StringOptional
    key: String
    name: String
    value: String
    member_of_groups: RelationshipManagerSync[CoreGroupSync]
    subscriber_of_groups: RelationshipManagerSync[CoreGroupSync]


class CoreMenuSync(CoreNodeSync):
    description: StringOptional
    icon: StringOptional
    kind: StringOptional
    label: StringOptional
    name: String
    namespace: String
    order_weight: Integer
    path: StringOptional
    protected: Boolean
    required_permissions: ListAttributeOptional
    section: String
    children: RelationshipManagerSync[CoreMenuSync]
    member_of_groups: RelationshipManagerSync[CoreGroupSync]
    parent: RelationshipAttributeSync[CoreMenuSync]
    subscriber_of_groups: RelationshipManagerSync[CoreGroupSync]


class CoreNodeTriggerMatchSync(CoreNodeSync):
    member_of_groups: RelationshipManagerSync[CoreGroupSync]
    subscriber_of_groups: RelationshipManagerSync[CoreGroupSync]
    trigger: RelationshipAttributeSync[CoreNodeTriggerRuleSync]


class CoreObjectComponentTemplateSync(CoreNodeSync):
    template_name: String
    member_of_groups: RelationshipManagerSync[CoreGroupSync]
    subscriber_of_groups: RelationshipManagerSync[CoreGroupSync]


class CoreObjectTemplateSync(CoreNodeSync):
    template_name: String
    member_of_groups: RelationshipManagerSync[CoreGroupSync]
    subscriber_of_groups: RelationshipManagerSync[CoreGroupSync]


class CoreProfileSync(CoreNodeSync):
    profile_name: String
    profile_priority: Integer
    member_of_groups: RelationshipManagerSync[CoreGroupSync]
    subscriber_of_groups: RelationshipManagerSync[CoreGroupSync]


class CoreResourcePoolSync(CoreNodeSync):
    description: StringOptional
    name: String
    member_of_groups: RelationshipManagerSync[CoreGroupSync]
    subscriber_of_groups: RelationshipManagerSync[CoreGroupSync]


class CoreTaskTargetSync(CoreNodeSync):
    member_of_groups: RelationshipManagerSync[CoreGroupSync]
    subscriber_of_groups: RelationshipManagerSync[CoreGroupSync]


class CoreThreadSync(CoreNodeSync):
    label: StringOptional
    resolved: Boolean
    change: RelationshipAttributeSync[CoreProposedChangeSync]
    comments: RelationshipManagerSync[CoreThreadCommentSync]
    member_of_groups: RelationshipManagerSync[CoreGroupSync]
    subscriber_of_groups: RelationshipManagerSync[CoreGroupSync]


class CoreTransformationSync(CoreNodeSync):
    dependencies: ListAttributeOptional
    dependencies_complete: BooleanOptional
    description: StringOptional
    fingerprint: StringOptional
    label: StringOptional
    name: String
    timeout: Integer
    artifact_definitions: RelationshipManagerSync[CoreArtifactDefinitionSync]
    member_of_groups: RelationshipManagerSync[CoreGroupSync]
    query: RelationshipAttributeSync[CoreGraphQLQuerySync]
    repository: RelationshipAttributeSync[CoreGenericRepositorySync]
    subscriber_of_groups: RelationshipManagerSync[CoreGroupSync]
    tags: RelationshipManagerSync[BuiltinTagSync]


class CoreTriggerRuleSync(CoreNodeSync):
    active: Boolean
    branch_scope: Dropdown
    description: StringOptional
    name: String
    action: RelationshipAttributeSync[CoreActionSync]
    member_of_groups: RelationshipManagerSync[CoreGroupSync]
    subscriber_of_groups: RelationshipManagerSync[CoreGroupSync]


class CoreValidatorSync(CoreNodeSync):
    completed_at: DateTimeOptional
    conclusion: String
    label: StringOptional
    started_at: DateTimeOptional
    state: String
    checks: RelationshipManagerSync[CoreCheckSync]
    member_of_groups: RelationshipManagerSync[CoreGroupSync]
    proposed_change: RelationshipAttributeSync[CoreProposedChangeSync]
    subscriber_of_groups: RelationshipManagerSync[CoreGroupSync]


class CoreWebhookSync(CoreNodeSync):
    active: Boolean
    branch_scope: Dropdown
    description: StringOptional
    event_type: String
    name: String
    node_kind: StringOptional
    url: URL
    validate_certificates: BooleanOptional
    headers: RelationshipManagerSync[CoreKeyValueSync]
    member_of_groups: RelationshipManagerSync[CoreGroupSync]
    subscriber_of_groups: RelationshipManagerSync[CoreGroupSync]


class CoreWeightedPoolResourceSync(CoreNodeSync):
    allocation_weight: IntegerOptional
    member_of_groups: RelationshipManagerSync[CoreGroupSync]
    subscriber_of_groups: RelationshipManagerSync[CoreGroupSync]


class LineageOwnerSync(CoreNodeSync):
    pass


class LineageSourceSync(CoreNodeSync):
    pass


class BuiltinTagSync(CoreNodeSync):
    description: StringOptional
    name: String
    member_of_groups: RelationshipManagerSync[CoreGroupSync]
    profiles: RelationshipManagerSync[CoreProfileSync]
    subscriber_of_groups: RelationshipManagerSync[CoreGroupSync]


class CoreAccountSync(LineageOwnerSync, LineageSourceSync, CoreGenericAccountSync):
    account_type: String
    description: StringOptional
    label: StringOptional
    name: String
    password: HashedPassword
    status: Dropdown
    member_of_groups: RelationshipManagerSync[CoreGroupSync]
    subscriber_of_groups: RelationshipManagerSync[CoreGroupSync]


class CoreAccountGroupSync(LineageOwnerSync, LineageSourceSync, CoreGroupSync):
    description: StringOptional
    group_type: String
    label: StringOptional
    name: String
    origin: StringOptional
    children: RelationshipManagerSync[CoreGroupSync]
    members: RelationshipManagerSync[CoreNodeSync]
    parent: RelationshipAttributeSync[CoreGroupSync]
    roles: RelationshipManagerSync[CoreAccountRoleSync]
    subscribers: RelationshipManagerSync[CoreNodeSync]


class CoreAccountRoleSync(CoreNodeSync):
    name: String
    groups: RelationshipManagerSync[CoreAccountGroupSync]
    member_of_groups: RelationshipManagerSync[CoreGroupSync]
    permissions: RelationshipManagerSync[CoreBasePermissionSync]
    subscriber_of_groups: RelationshipManagerSync[CoreGroupSync]


class CoreArtifactSync(CoreTaskTargetSync):
    checksum: StringOptional
    content_type: String
    name: String
    parameters: JSONAttributeOptional
    status: String
    storage_id: StringOptional
    definition: RelationshipAttributeSync[CoreArtifactDefinitionSync]
    member_of_groups: RelationshipManagerSync[CoreGroupSync]
    object: RelationshipAttributeSync[CoreArtifactTargetSync]
    subscriber_of_groups: RelationshipManagerSync[CoreGroupSync]


class CoreArtifactCheckSync(CoreCheckSync):
    artifact_id: StringOptional
    changed: BooleanOptional
    checksum: StringOptional
    conclusion: String
    created_at: DateTimeOptional
    kind: String
    label: StringOptional
    line_number: IntegerOptional
    message: StringOptional
    name: StringOptional
    origin: String
    severity: String
    storage_id: StringOptional
    member_of_groups: RelationshipManagerSync[CoreGroupSync]
    subscriber_of_groups: RelationshipManagerSync[CoreGroupSync]
    validator: RelationshipAttributeSync[CoreValidatorSync]


class CoreArtifactDefinitionSync(CoreTaskTargetSync):
    artifact_name: String
    content_type: String
    description: StringOptional
    fingerprint: StringOptional
    name: String
    parameters: JSONAttribute
    artifacts: RelationshipManagerSync[CoreArtifactSync]
    member_of_groups: RelationshipManagerSync[CoreGroupSync]
    subscriber_of_groups: RelationshipManagerSync[CoreGroupSync]
    targets: RelationshipAttributeSync[CoreGroupSync]
    transformation: RelationshipAttributeSync[CoreTransformationSync]
    validators: RelationshipManagerSync[CoreArtifactValidatorSync]


class CoreArtifactThreadSync(CoreThreadSync):
    artifact_id: StringOptional
    label: StringOptional
    line_number: IntegerOptional
    resolved: Boolean
    storage_id: StringOptional
    change: RelationshipAttributeSync[CoreProposedChangeSync]
    comments: RelationshipManagerSync[CoreThreadCommentSync]
    member_of_groups: RelationshipManagerSync[CoreGroupSync]
    subscriber_of_groups: RelationshipManagerSync[CoreGroupSync]


class CoreArtifactValidatorSync(CoreValidatorSync):
    completed_at: DateTimeOptional
    conclusion: String
    label: StringOptional
    started_at: DateTimeOptional
    state: String
    checks: RelationshipManagerSync[CoreCheckSync]
    definition: RelationshipAttributeSync[CoreArtifactDefinitionSync]
    member_of_groups: RelationshipManagerSync[CoreGroupSync]
    proposed_change: RelationshipAttributeSync[CoreProposedChangeSync]
    subscriber_of_groups: RelationshipManagerSync[CoreGroupSync]


class CoreChangeCommentSync(CoreCommentSync):
    text: String
    change: RelationshipAttributeSync[CoreProposedChangeSync]
    member_of_groups: RelationshipManagerSync[CoreGroupSync]
    subscriber_of_groups: RelationshipManagerSync[CoreGroupSync]


class CoreChangeThreadSync(CoreThreadSync):
    label: StringOptional
    resolved: Boolean
    change: RelationshipAttributeSync[CoreProposedChangeSync]
    comments: RelationshipManagerSync[CoreThreadCommentSync]
    member_of_groups: RelationshipManagerSync[CoreGroupSync]
    subscriber_of_groups: RelationshipManagerSync[CoreGroupSync]


class CoreCheckDefinitionSync(CoreTaskTargetSync):
    class_name: String
    description: StringOptional
    file_path: String
    name: String
    parameters: JSONAttributeOptional
    timeout: Integer
    member_of_groups: RelationshipManagerSync[CoreGroupSync]
    query: RelationshipAttributeSync[CoreGraphQLQuerySync]
    repository: RelationshipAttributeSync[CoreGenericRepositorySync]
    subscriber_of_groups: RelationshipManagerSync[CoreGroupSync]
    tags: RelationshipManagerSync[BuiltinTagSync]
    targets: RelationshipAttributeSync[CoreGroupSync]
    validators: RelationshipManagerSync[CoreUserValidatorSync]


class CoreCustomWebhookSync(CoreWebhookSync, CoreTaskTargetSync):
    active: Boolean
    branch_scope: Dropdown
    description: StringOptional
    event_type: String
    name: String
    node_kind: StringOptional
    shared_key: StringOptional
    url: URL
    validate_certificates: BooleanOptional
    headers: RelationshipManagerSync[CoreKeyValueSync]
    member_of_groups: RelationshipManagerSync[CoreGroupSync]
    subscriber_of_groups: RelationshipManagerSync[CoreGroupSync]
    transformation: RelationshipAttributeSync[CoreTransformPythonSync]


class CoreDataCheckSync(CoreCheckSync):
    conclusion: String
    conflicts: JSONAttribute
    created_at: DateTimeOptional
    enriched_conflict_id: StringOptional
    keep_branch: StringOptional
    kind: String
    label: StringOptional
    message: StringOptional
    name: StringOptional
    origin: String
    severity: String
    member_of_groups: RelationshipManagerSync[CoreGroupSync]
    subscriber_of_groups: RelationshipManagerSync[CoreGroupSync]
    validator: RelationshipAttributeSync[CoreValidatorSync]


class CoreDataValidatorSync(CoreValidatorSync):
    completed_at: DateTimeOptional
    conclusion: String
    label: StringOptional
    started_at: DateTimeOptional
    state: String
    checks: RelationshipManagerSync[CoreCheckSync]
    member_of_groups: RelationshipManagerSync[CoreGroupSync]
    proposed_change: RelationshipAttributeSync[CoreProposedChangeSync]
    subscriber_of_groups: RelationshipManagerSync[CoreGroupSync]


class CoreEnvKeyValueSync(CoreKeyValueSync):
    description: StringOptional
    key: String
    name: String
    value: String
    member_of_groups: RelationshipManagerSync[CoreGroupSync]
    subscriber_of_groups: RelationshipManagerSync[CoreGroupSync]


class CoreFileCheckSync(CoreCheckSync):
    commit: StringOptional
    conclusion: String
    created_at: DateTimeOptional
    files: ListAttributeOptional
    kind: String
    label: StringOptional
    message: StringOptional
    name: StringOptional
    origin: String
    severity: String
    member_of_groups: RelationshipManagerSync[CoreGroupSync]
    subscriber_of_groups: RelationshipManagerSync[CoreGroupSync]
    validator: RelationshipAttributeSync[CoreValidatorSync]


class CoreFileThreadSync(CoreThreadSync):
    commit: StringOptional
    file: StringOptional
    label: StringOptional
    line_number: IntegerOptional
    resolved: Boolean
    change: RelationshipAttributeSync[CoreProposedChangeSync]
    comments: RelationshipManagerSync[CoreThreadCommentSync]
    member_of_groups: RelationshipManagerSync[CoreGroupSync]
    repository: RelationshipAttributeSync[CoreRepositorySync]
    subscriber_of_groups: RelationshipManagerSync[CoreGroupSync]


class CoreGeneratorActionSync(CoreActionSync):
    description: StringOptional
    name: String
    generator: RelationshipAttributeSync[CoreGeneratorDefinitionSync]
    member_of_groups: RelationshipManagerSync[CoreGroupSync]
    subscriber_of_groups: RelationshipManagerSync[CoreGroupSync]
    triggers: RelationshipManagerSync[CoreTriggerRuleSync]


class CoreGeneratorAwareGroupSync(CoreGroupSync):
    description: StringOptional
    group_type: String
    label: StringOptional
    name: String
    children: RelationshipManagerSync[CoreGroupSync]
    members: RelationshipManagerSync[CoreNodeSync]
    parent: RelationshipAttributeSync[CoreGroupSync]
    subscribers: RelationshipManagerSync[CoreNodeSync]


class CoreGeneratorCheckSync(CoreCheckSync):
    conclusion: String
    created_at: DateTimeOptional
    instance: String
    kind: String
    label: StringOptional
    message: StringOptional
    name: StringOptional
    origin: String
    severity: String
    member_of_groups: RelationshipManagerSync[CoreGroupSync]
    subscriber_of_groups: RelationshipManagerSync[CoreGroupSync]
    validator: RelationshipAttributeSync[CoreValidatorSync]


class CoreGeneratorDefinitionSync(CoreTaskTargetSync):
    class_name: String
    convert_query_response: Boolean
    dependencies: ListAttributeOptional
    dependencies_complete: BooleanOptional
    description: StringOptional
    execute_after_merge: Boolean
    execute_in_proposed_change: Boolean
    file_path: String
    fingerprint: StringOptional
    name: String
    parameters: JSONAttribute
    instances: RelationshipManagerSync[CoreGeneratorInstanceSync]
    member_of_groups: RelationshipManagerSync[CoreGroupSync]
    query: RelationshipAttributeSync[CoreGraphQLQuerySync]
    repository: RelationshipAttributeSync[CoreGenericRepositorySync]
    subscriber_of_groups: RelationshipManagerSync[CoreGroupSync]
    targets: RelationshipAttributeSync[CoreGroupSync]
    validators: RelationshipManagerSync[CoreGeneratorValidatorSync]


class CoreGeneratorGroupSync(CoreGroupSync):
    description: StringOptional
    group_type: String
    label: StringOptional
    name: String
    children: RelationshipManagerSync[CoreGroupSync]
    members: RelationshipManagerSync[CoreNodeSync]
    parent: RelationshipAttributeSync[CoreGroupSync]
    subscribers: RelationshipManagerSync[CoreNodeSync]


class CoreGeneratorInstanceSync(CoreTaskTargetSync):
    name: String
    status: String
    definition: RelationshipAttributeSync[CoreGeneratorDefinitionSync]
    member_of_groups: RelationshipManagerSync[CoreGroupSync]
    object: RelationshipAttributeSync[CoreNodeSync]
    subscriber_of_groups: RelationshipManagerSync[CoreGroupSync]


class CoreGeneratorValidatorSync(CoreValidatorSync):
    completed_at: DateTimeOptional
    conclusion: String
    label: StringOptional
    started_at: DateTimeOptional
    state: String
    checks: RelationshipManagerSync[CoreCheckSync]
    definition: RelationshipAttributeSync[CoreGeneratorDefinitionSync]
    member_of_groups: RelationshipManagerSync[CoreGroupSync]
    proposed_change: RelationshipAttributeSync[CoreProposedChangeSync]
    subscriber_of_groups: RelationshipManagerSync[CoreGroupSync]


class CoreGlobalPermissionSync(CoreBasePermissionSync):
    action: Dropdown
    decision: Integer
    description: StringOptional
    identifier: StringOptional
    member_of_groups: RelationshipManagerSync[CoreGroupSync]
    roles: RelationshipManagerSync[CoreAccountRoleSync]
    subscriber_of_groups: RelationshipManagerSync[CoreGroupSync]


class CoreGraphQLQuerySync(CoreNodeSync):
    depth: IntegerOptional
    description: StringOptional
    fingerprint: StringOptional
    height: IntegerOptional
    models: ListAttributeOptional
    name: String
    operations: ListAttributeOptional
    query: String
    variables: JSONAttributeOptional
    member_of_groups: RelationshipManagerSync[CoreGroupSync]
    query_groups: RelationshipManagerSync[CoreGraphQLQueryGroupSync]
    repository: RelationshipAttributeSync[CoreGenericRepositorySync]
    subscriber_of_groups: RelationshipManagerSync[CoreGroupSync]
    tags: RelationshipManagerSync[BuiltinTagSync]


class CoreGraphQLQueryGroupSync(CoreGroupSync):
    description: StringOptional
    group_type: String
    label: StringOptional
    name: String
    parameters: JSONAttributeOptional
    children: RelationshipManagerSync[CoreGroupSync]
    members: RelationshipManagerSync[CoreNodeSync]
    parent: RelationshipAttributeSync[CoreGroupSync]
    query: RelationshipAttributeSync[CoreGraphQLQuerySync]
    subscribers: RelationshipManagerSync[CoreNodeSync]


class CoreGroupActionSync(CoreActionSync):
    description: StringOptional
    member_action: Dropdown
    name: String
    group: RelationshipAttributeSync[CoreGroupSync]
    member_of_groups: RelationshipManagerSync[CoreGroupSync]
    subscriber_of_groups: RelationshipManagerSync[CoreGroupSync]
    triggers: RelationshipManagerSync[CoreTriggerRuleSync]


class CoreGroupTriggerRuleSync(CoreTriggerRuleSync):
    active: Boolean
    branch_scope: Dropdown
    description: StringOptional
    member_update: Dropdown
    name: String
    action: RelationshipAttributeSync[CoreActionSync]
    group: RelationshipAttributeSync[CoreGroupSync]
    member_of_groups: RelationshipManagerSync[CoreGroupSync]
    subscriber_of_groups: RelationshipManagerSync[CoreGroupSync]


class CoreIPAddressPoolSync(CoreResourcePoolSync, LineageSourceSync, CoreIPPoolSync):
    default_address_type: String
    default_prefix_length: IntegerOptional
    description: StringOptional
    name: String
    ip_namespace: RelationshipAttributeSync[BuiltinIPNamespaceSync]
    member_of_groups: RelationshipManagerSync[CoreGroupSync]
    resources: RelationshipManagerSync[BuiltinIPPrefixSync]
    subscriber_of_groups: RelationshipManagerSync[CoreGroupSync]


class CoreIPPrefixPoolSync(CoreResourcePoolSync, LineageSourceSync, CoreIPPoolSync):
    default_member_type: String
    default_prefix_length: IntegerOptional
    default_prefix_type: StringOptional
    description: StringOptional
    name: String
    ip_namespace: RelationshipAttributeSync[BuiltinIPNamespaceSync]
    member_of_groups: RelationshipManagerSync[CoreGroupSync]
    resources: RelationshipManagerSync[BuiltinIPPrefixSync]
    subscriber_of_groups: RelationshipManagerSync[CoreGroupSync]


class CoreMenuItemSync(CoreMenuSync):
    description: StringOptional
    icon: StringOptional
    kind: StringOptional
    label: StringOptional
    name: String
    namespace: String
    order_weight: Integer
    path: StringOptional
    protected: Boolean
    required_permissions: ListAttributeOptional
    section: String
    children: RelationshipManagerSync[CoreMenuSync]
    member_of_groups: RelationshipManagerSync[CoreGroupSync]
    parent: RelationshipAttributeSync[CoreMenuSync]
    subscriber_of_groups: RelationshipManagerSync[CoreGroupSync]


class CoreNodeTriggerAttributeMatchSync(CoreNodeTriggerMatchSync):
    attribute_name: String
    value: StringOptional
    value_match: Dropdown
    value_previous: StringOptional
    member_of_groups: RelationshipManagerSync[CoreGroupSync]
    subscriber_of_groups: RelationshipManagerSync[CoreGroupSync]
    trigger: RelationshipAttributeSync[CoreNodeTriggerRuleSync]


class CoreNodeTriggerRelationshipMatchSync(CoreNodeTriggerMatchSync):
    modification_type: Dropdown
    peer: StringOptional
    relationship_name: String
    member_of_groups: RelationshipManagerSync[CoreGroupSync]
    subscriber_of_groups: RelationshipManagerSync[CoreGroupSync]
    trigger: RelationshipAttributeSync[CoreNodeTriggerRuleSync]


class CoreNodeTriggerRuleSync(CoreTriggerRuleSync):
    active: Boolean
    branch_scope: Dropdown
    description: StringOptional
    mutation_action: String
    name: String
    node_kind: String
    action: RelationshipAttributeSync[CoreActionSync]
    matches: RelationshipManagerSync[CoreNodeTriggerMatchSync]
    member_of_groups: RelationshipManagerSync[CoreGroupSync]
    subscriber_of_groups: RelationshipManagerSync[CoreGroupSync]


class CoreNumberPoolSync(CoreResourcePoolSync, LineageSourceSync):
    description: StringOptional
    end_range: Integer
    name: String
    node: String
    node_attribute: String
    pool_type: String
    start_range: Integer
    member_of_groups: RelationshipManagerSync[CoreGroupSync]
    subscriber_of_groups: RelationshipManagerSync[CoreGroupSync]


class CoreObjectPermissionSync(CoreBasePermissionSync):
    action: String
    decision: Integer
    description: StringOptional
    identifier: StringOptional
    name: String
    namespace: String
    member_of_groups: RelationshipManagerSync[CoreGroupSync]
    roles: RelationshipManagerSync[CoreAccountRoleSync]
    subscriber_of_groups: RelationshipManagerSync[CoreGroupSync]


class CoreObjectThreadSync(CoreThreadSync):
    label: StringOptional
    object_path: String
    resolved: Boolean
    change: RelationshipAttributeSync[CoreProposedChangeSync]
    comments: RelationshipManagerSync[CoreThreadCommentSync]
    member_of_groups: RelationshipManagerSync[CoreGroupSync]
    subscriber_of_groups: RelationshipManagerSync[CoreGroupSync]


class CorePasswordCredentialSync(CoreCredentialSync):
    description: StringOptional
    label: StringOptional
    name: String
    password: StringOptional
    username: StringOptional
    member_of_groups: RelationshipManagerSync[CoreGroupSync]
    subscriber_of_groups: RelationshipManagerSync[CoreGroupSync]


class CoreProposedChangeSync(CoreTaskTargetSync):
    description: StringOptional
    destination_branch: String
    is_draft: Boolean
    name: String
    source_branch: String
    state: String
    total_comments: IntegerOptional
    approved_by: RelationshipManagerSync[CoreGenericAccountSync]
    comments: RelationshipManagerSync[CoreChangeCommentSync]
    member_of_groups: RelationshipManagerSync[CoreGroupSync]
    rejected_by: RelationshipManagerSync[CoreGenericAccountSync]
    reviewers: RelationshipManagerSync[CoreGenericAccountSync]
    subscriber_of_groups: RelationshipManagerSync[CoreGroupSync]
    threads: RelationshipManagerSync[CoreThreadSync]
    validations: RelationshipManagerSync[CoreValidatorSync]


class CoreReadOnlyRepositorySync(LineageOwnerSync, LineageSourceSync, CoreGenericRepositorySync, CoreTaskTargetSync):
    commit: StringOptional
    description: StringOptional
    internal_status: Dropdown
    location: String
    name: String
    operational_status: Dropdown
    ref: String
    sync_status: Dropdown
    checks: RelationshipManagerSync[CoreCheckDefinitionSync]
    credential: RelationshipAttributeSync[CoreCredentialSync]
    generators: RelationshipManagerSync[CoreGeneratorDefinitionSync]
    groups_objects: RelationshipManagerSync[CoreRepositoryGroupSync]
    member_of_groups: RelationshipManagerSync[CoreGroupSync]
    queries: RelationshipManagerSync[CoreGraphQLQuerySync]
    subscriber_of_groups: RelationshipManagerSync[CoreGroupSync]
    tags: RelationshipManagerSync[BuiltinTagSync]
    transformations: RelationshipManagerSync[CoreTransformationSync]


class CoreRepositorySync(LineageOwnerSync, LineageSourceSync, CoreGenericRepositorySync, CoreTaskTargetSync):
    commit: StringOptional
    default_branch: String
    description: StringOptional
    internal_status: Dropdown
    location: String
    name: String
    operational_status: Dropdown
    sync_status: Dropdown
    checks: RelationshipManagerSync[CoreCheckDefinitionSync]
    credential: RelationshipAttributeSync[CoreCredentialSync]
    generators: RelationshipManagerSync[CoreGeneratorDefinitionSync]
    groups_objects: RelationshipManagerSync[CoreRepositoryGroupSync]
    member_of_groups: RelationshipManagerSync[CoreGroupSync]
    queries: RelationshipManagerSync[CoreGraphQLQuerySync]
    subscriber_of_groups: RelationshipManagerSync[CoreGroupSync]
    tags: RelationshipManagerSync[BuiltinTagSync]
    transformations: RelationshipManagerSync[CoreTransformationSync]


class CoreRepositoryGroupSync(CoreGroupSync):
    content: Dropdown
    description: StringOptional
    group_type: String
    label: StringOptional
    name: String
    children: RelationshipManagerSync[CoreGroupSync]
    members: RelationshipManagerSync[CoreNodeSync]
    parent: RelationshipAttributeSync[CoreGroupSync]
    repository: RelationshipAttributeSync[CoreGenericRepositorySync]
    subscribers: RelationshipManagerSync[CoreNodeSync]


class CoreRepositoryValidatorSync(CoreValidatorSync):
    completed_at: DateTimeOptional
    conclusion: String
    label: StringOptional
    started_at: DateTimeOptional
    state: String
    checks: RelationshipManagerSync[CoreCheckSync]
    member_of_groups: RelationshipManagerSync[CoreGroupSync]
    proposed_change: RelationshipAttributeSync[CoreProposedChangeSync]
    repository: RelationshipAttributeSync[CoreGenericRepositorySync]
    subscriber_of_groups: RelationshipManagerSync[CoreGroupSync]


class CoreSchemaCheckSync(CoreCheckSync):
    conclusion: String
    conflicts: JSONAttribute
    created_at: DateTimeOptional
    enriched_conflict_id: StringOptional
    kind: String
    label: StringOptional
    message: StringOptional
    name: StringOptional
    origin: String
    severity: String
    member_of_groups: RelationshipManagerSync[CoreGroupSync]
    subscriber_of_groups: RelationshipManagerSync[CoreGroupSync]
    validator: RelationshipAttributeSync[CoreValidatorSync]


class CoreSchemaValidatorSync(CoreValidatorSync):
    completed_at: DateTimeOptional
    conclusion: String
    label: StringOptional
    started_at: DateTimeOptional
    state: String
    checks: RelationshipManagerSync[CoreCheckSync]
    member_of_groups: RelationshipManagerSync[CoreGroupSync]
    proposed_change: RelationshipAttributeSync[CoreProposedChangeSync]
    subscriber_of_groups: RelationshipManagerSync[CoreGroupSync]


class CoreStandardCheckSync(CoreCheckSync):
    conclusion: String
    created_at: DateTimeOptional
    kind: String
    label: StringOptional
    message: StringOptional
    name: StringOptional
    origin: String
    severity: String
    member_of_groups: RelationshipManagerSync[CoreGroupSync]
    subscriber_of_groups: RelationshipManagerSync[CoreGroupSync]
    validator: RelationshipAttributeSync[CoreValidatorSync]


class CoreStandardGroupSync(CoreGroupSync):
    description: StringOptional
    group_type: String
    label: StringOptional
    name: String
    children: RelationshipManagerSync[CoreGroupSync]
    members: RelationshipManagerSync[CoreNodeSync]
    parent: RelationshipAttributeSync[CoreGroupSync]
    subscribers: RelationshipManagerSync[CoreNodeSync]


class CoreStandardWebhookSync(CoreWebhookSync, CoreTaskTargetSync):
    active: Boolean
    branch_scope: Dropdown
    description: StringOptional
    event_type: String
    name: String
    node_kind: StringOptional
    shared_key: String
    url: URL
    validate_certificates: BooleanOptional
    headers: RelationshipManagerSync[CoreKeyValueSync]
    member_of_groups: RelationshipManagerSync[CoreGroupSync]
    subscriber_of_groups: RelationshipManagerSync[CoreGroupSync]


class CoreStaticKeyValueSync(CoreKeyValueSync):
    description: StringOptional
    key: String
    name: String
    value: String
    member_of_groups: RelationshipManagerSync[CoreGroupSync]
    subscriber_of_groups: RelationshipManagerSync[CoreGroupSync]


class CoreThreadCommentSync(CoreCommentSync):
    text: String
    member_of_groups: RelationshipManagerSync[CoreGroupSync]
    subscriber_of_groups: RelationshipManagerSync[CoreGroupSync]
    thread: RelationshipAttributeSync[CoreThreadSync]


class CoreTransformJinja2Sync(CoreTransformationSync):
    dependencies: ListAttributeOptional
    dependencies_complete: BooleanOptional
    description: StringOptional
    fingerprint: StringOptional
    label: StringOptional
    name: String
    template_path: String
    timeout: Integer
    artifact_definitions: RelationshipManagerSync[CoreArtifactDefinitionSync]
    member_of_groups: RelationshipManagerSync[CoreGroupSync]
    query: RelationshipAttributeSync[CoreGraphQLQuerySync]
    repository: RelationshipAttributeSync[CoreGenericRepositorySync]
    subscriber_of_groups: RelationshipManagerSync[CoreGroupSync]
    tags: RelationshipManagerSync[BuiltinTagSync]


class CoreTransformPythonSync(CoreTransformationSync):
    class_name: String
    convert_query_response: Boolean
    dependencies: ListAttributeOptional
    dependencies_complete: BooleanOptional
    description: StringOptional
    file_path: String
    fingerprint: StringOptional
    label: StringOptional
    name: String
    timeout: Integer
    artifact_definitions: RelationshipManagerSync[CoreArtifactDefinitionSync]
    member_of_groups: RelationshipManagerSync[CoreGroupSync]
    query: RelationshipAttributeSync[CoreGraphQLQuerySync]
    repository: RelationshipAttributeSync[CoreGenericRepositorySync]
    subscriber_of_groups: RelationshipManagerSync[CoreGroupSync]
    tags: RelationshipManagerSync[BuiltinTagSync]


class CoreUserValidatorSync(CoreValidatorSync):
    completed_at: DateTimeOptional
    conclusion: String
    label: StringOptional
    started_at: DateTimeOptional
    state: String
    check_definition: RelationshipAttributeSync[CoreCheckDefinitionSync]
    checks: RelationshipManagerSync[CoreCheckSync]
    member_of_groups: RelationshipManagerSync[CoreGroupSync]
    proposed_change: RelationshipAttributeSync[CoreProposedChangeSync]
    repository: RelationshipAttributeSync[CoreGenericRepositorySync]
    subscriber_of_groups: RelationshipManagerSync[CoreGroupSync]


class InternalAccountTokenSync(CoreNodeSync):
    expiration: DateTimeOptional
    name: StringOptional
    token: String
    account: RelationshipAttributeSync[CoreGenericAccountSync]
    member_of_groups: RelationshipManagerSync[CoreGroupSync]
    subscriber_of_groups: RelationshipManagerSync[CoreGroupSync]


class InternalExternalIdentitySync(CoreNodeSync):
    protocol: String
    provider_name: String
    sub: String
    account: RelationshipAttributeSync[CoreGenericAccountSync]
    member_of_groups: RelationshipManagerSync[CoreGroupSync]
    subscriber_of_groups: RelationshipManagerSync[CoreGroupSync]


class InternalIPPrefixAvailableSync(BuiltinIPPrefixSync):
    broadcast_address: StringOptional
    description: StringOptional
    hostmask: StringOptional
    is_pool: Boolean
    is_top_level: BooleanOptional
    member_type: Dropdown
    netmask: StringOptional
    network_address: StringOptional
    prefix: IPNetwork
    utilization: IntegerOptional
    children: RelationshipManagerSync[BuiltinIPPrefixSync]
    ip_addresses: RelationshipManagerSync[BuiltinIPAddressSync]
    ip_namespace: RelationshipAttributeSync[BuiltinIPNamespaceSync]
    member_of_groups: RelationshipManagerSync[CoreGroupSync]
    parent: RelationshipAttributeSync[BuiltinIPPrefixSync]
    profiles: RelationshipManagerSync[CoreProfileSync]
    resource_pool: RelationshipManagerSync[CoreIPPoolSync]
    subscriber_of_groups: RelationshipManagerSync[CoreGroupSync]


class InternalIPRangeAvailableSync(BuiltinIPAddressSync):
    address: IPHost
    description: StringOptional
    last_address: IPHost
    ip_namespace: RelationshipAttributeSync[BuiltinIPNamespaceSync]
    ip_prefix: RelationshipAttributeSync[BuiltinIPPrefixSync]
    member_of_groups: RelationshipManagerSync[CoreGroupSync]
    profiles: RelationshipManagerSync[CoreProfileSync]
    subscriber_of_groups: RelationshipManagerSync[CoreGroupSync]


class InternalRefreshTokenSync(CoreNodeSync):
    expiration: DateTime
    account: RelationshipAttributeSync[CoreGenericAccountSync]
    member_of_groups: RelationshipManagerSync[CoreGroupSync]
    subscriber_of_groups: RelationshipManagerSync[CoreGroupSync]


class IpamNamespaceSync(BuiltinIPNamespaceSync):
    default: BooleanOptional
    description: StringOptional
    name: String
    ip_addresses: RelationshipManagerSync[BuiltinIPAddressSync]
    ip_prefixes: RelationshipManagerSync[BuiltinIPPrefixSync]
    member_of_groups: RelationshipManagerSync[CoreGroupSync]
    profiles: RelationshipManagerSync[CoreProfileSync]
    subscriber_of_groups: RelationshipManagerSync[CoreGroupSync]


class ProfileBuiltinIPAddressSync(LineageSourceSync, CoreProfileSync, CoreNodeSync):
    address: IPHostOptional
    description: StringOptional
    profile_name: String
    profile_priority: Integer
    ip_namespace: RelationshipAttributeSync[BuiltinIPNamespaceSync]
    member_of_groups: RelationshipManagerSync[CoreGroupSync]
    related_nodes: RelationshipManagerSync[BuiltinIPAddressSync]
    subscriber_of_groups: RelationshipManagerSync[CoreGroupSync]


class ProfileBuiltinIPPrefixSync(LineageSourceSync, CoreProfileSync, CoreNodeSync):
    description: StringOptional
    is_pool: BooleanOptional
    member_type: DropdownOptional
    prefix: IPNetworkOptional
    profile_name: String
    profile_priority: Integer
    ip_namespace: RelationshipAttributeSync[BuiltinIPNamespaceSync]
    member_of_groups: RelationshipManagerSync[CoreGroupSync]
    related_nodes: RelationshipManagerSync[BuiltinIPPrefixSync]
    subscriber_of_groups: RelationshipManagerSync[CoreGroupSync]


class ProfileBuiltinTagSync(LineageSourceSync, CoreProfileSync, CoreNodeSync):
    description: StringOptional
    profile_name: String
    profile_priority: Integer
    member_of_groups: RelationshipManagerSync[CoreGroupSync]
    related_nodes: RelationshipManagerSync[BuiltinTagSync]
    subscriber_of_groups: RelationshipManagerSync[CoreGroupSync]


class ProfileIpamNamespaceSync(LineageSourceSync, CoreProfileSync, CoreNodeSync):
    description: StringOptional
    profile_name: String
    profile_priority: Integer
    ip_addresses: RelationshipManagerSync[BuiltinIPAddressSync]
    ip_prefixes: RelationshipManagerSync[BuiltinIPPrefixSync]
    member_of_groups: RelationshipManagerSync[CoreGroupSync]
    related_nodes: RelationshipManagerSync[IpamNamespaceSync]
    subscriber_of_groups: RelationshipManagerSync[CoreGroupSync]
