---
# yamllint disable rule:truthy
name: Publish Infrahub SDK Package

on:
  workflow_dispatch:
    inputs:
      runs-on:
        description: "The OS to run the job on"
        required: false
        default: "ubuntu-22.04"
        type: string
      publish:
        type: boolean
        description: Whether to publish the package to Pypi
        required: false
        default: false
  workflow_call:
    inputs:
      runs-on:
        description: "The OS to run the job on"
        required: false
        default: "ubuntu-22.04"
        type: string
      publish:
        type: boolean
        description: Whether to publish the package to Pypi
        required: false
        default: false

jobs:
  publish_to_pypi:
    name: "Publish Infrahub SDK to PyPI"
    runs-on: "ubuntu-22.04"
    steps:
      - name: "Set up Python"
        uses: "actions/setup-python@v5"
        with:
          python-version: "3.12"

      - name: "Install uv"
        run: |
          pipx install uv

      - name: "Check out repository code"
        uses: "actions/checkout@v4"
        with:
          submodules: true

      - name: "Cache uv venv"
        uses: "actions/cache@v4"
        id: "cached-uv-dependencies"
        with:
          path: "./python_sdk/.venv"
          key: "venv-${{ runner.os }}-${{ hashFiles('**/pyproject.toml') }}"

      - name: "Install Dependencies"
        run: "uv pip install --all-extras -r pyproject.toml"
        if: steps.cached-uv-dependencies.outputs.cache-hit != 'true'

      - name: "Add PyPI secret"
        run: "uv pip config set pypi-token.pypi ${{ secrets.PYPI_TOKEN }}"

      - name: "Build package"
        run: "uv build"

      - name: "show output"
        run: "ls -la dist/"

      - name: "Publish to PyPI"
        if: ${{ inputs.publish }}
        run: "uv publish"
